=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/recipebook.dtd
<!--

RecipeXML - An XML recipe markup language.

Copyright (C) 2005 David Horton
This work is licensed under the Creative Commons Attribution Share-Alike
license.  See http://creativecommons.org/licenses/by/2.0/ for details.

Modified 2014 Richard Newman

-->


<!-- === REQUIRED Hyperlinks for URL references === -->

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink url CDATA #REQUIRED>


<!-- === OPTIONAL  Information about a recipe === -->

<!ELEMENT author (#PCDATA)>
<!ELEMENT blurb (#PCDATA)>
<!ELEMENT effort (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT preptime (#PCDATA)>
<!ELEMENT source (#PCDATA|hyperlink)*>
<!ELEMENT yield (#PCDATA)>


<!-- === REQUIRED Lists of ingredients === -->

<!ELEMENT fooditem (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!-- FIXME? The mixed-content definition below does not enforce one and
     only one instance of the tags quantity, unit and fooditem. -->
<!ELEMENT ingredient (#PCDATA | quantity | unit | fooditem)*>


<!-- === REQUIRED Elements of preparation === -->

<!ELEMENT equipment (#PCDATA | hyperlink)*>
<!ELEMENT step (#PCDATA | equipment | hyperlink)*>

<!-- === OPTIONAL Elements of preparation === -->
<!-- === MODIFIED Elements of preparation === -->

<!ELEMENT equipmentinv (#PCDATA?, quantity?, equipment)>
<!ELEMENT timeamt (#PCDATA)>
<!ELEMENT timeunit (#PCDATA)>
<!ELEMENT timetype (#PCDATA)>
<!ELEMENT steptime (#PCDATA?, (timeamt, timeunit, timetype?)+)>
<!ELEMENT timedstep (#PCDATA?, step, steptime?)>


<!-- === REQUIRED The main elements of a recipe === -->
<!-- === REQUIRED title, ingredientlist, and preparation  === -->
<!-- === OPTIONAL recipeinfo, serving, notes  === -->

<!ELEMENT title (#PCDATA)>
<!ELEMENT recipeinfo (author | blurb | effort | genre | preptime | source | yield)*>
<!ELEMENT ingredientlist (ingredient)*>
<!ELEMENT preparation (#PCDATA | equipment | step | timedstep | hyperlink)*>
<!ELEMENT serving (#PCDATA | hyperlink)*>
<!ELEMENT notes (#PCDATA | hyperlink)*>


<!-- === REQUIRED And finally, the recipe itself === -->
<!-- === OPTIONAL all items noted with "?" are optional === -->

<!ELEMENT recipe (title, recipeinfo?, ingredientlist, preparation, serving?, notes?)>


<!-- === The following elements provide logical groupings of recipes === -->


<!-- ===  OPTIONAL A section provides logical divisions of a cookbook === -->

<!ELEMENT section (title, recipe+)>


<!-- ===  REQUIRED A cookbook consists of one or more recipes or sections === -->
<!-- ===  MODIFIED so that title is optional  === -->
<!ELEMENT cookbook (title?, (section | recipe)+)>

<!-- ===  REQUIRED inventory === -->

<!ELEMENT equipmentlist (equipment)*>

<!ELEMENT inventory (ingredientlist | equipmentlist)+>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/pancakes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<recipe>
  <title>Hippie Pancakes</title>

  <recipeinfo>
    <blurb>Socially conscious breakfast food.</blurb>

    <author>David Horton</author>

    <yield>12 to 16 small pancakes, enough for two hippies</yield>

    <preptime>10 minutes</preptime>
  </recipeinfo>

  <ingredientlist>
    <ingredient><quantity>1</quantity> <unit>C.</unit> <fooditem>unbleached
    wheat blend flour</fooditem></ingredient>

    <ingredient><quantity>2</quantity> <unit>tsp.</unit> <fooditem>baking
    powder</fooditem></ingredient>

    <ingredient><quantity>1</quantity> <unit>tsp.</unit> <fooditem>unrefined
    sugar</fooditem></ingredient>

    <ingredient><quantity>1/4</quantity> <unit>tsp.</unit> <fooditem>coarse
    kosher salt</fooditem></ingredient>

    <ingredient><quantity>1</quantity> <fooditem>free-range egg
    </fooditem></ingredient>

    <ingredient><quantity>1 1/4</quantity> <unit>C.</unit>
    <fooditem>hormone-free milk</fooditem></ingredient>

    <ingredient><quantity>1</quantity> <unit>tsp.</unit> <fooditem>organic
    vegetable oil</fooditem></ingredient>
  </ingredientlist>

  <preparation>Pre-heat griddle over medium heat. Combine dry ingredients in a
  <equipment>mixing bowl</equipment>. Stir in egg, milk and oil. Use a large
  spoon or gravy ladle to transfer pancake batter to the
  <equipment>griddle</equipment>. Pancakes are ready to flip when large
  bubbles can be seen on top.</preparation>

  <serving>Top with fruit and berries or serve with traditional maple
  syrup.</serving>

  <notes>All-purpose flour may be used instead of wheat blend, but decrease
  the milk by 1/4 C and cut the baking powder by 1/2 tsp. You may also replace
  the unrefined sugar with brown sugar and yes, regular eggs work too, but at
  this point you have completely sold out to The Man and may as well just hop
  in your beemer and drive to some trendy, over-priced, yuppie pancake house
  and get it over with.</notes>
</recipe>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/COP3503su14_Proj3_WenlanT/supplies2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventory PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
 
<inventory>
  <ingredientlist>
    <ingredient>
      <quantity>24</quantity> 
      <unit>Tsp</unit> 
      <fooditem>Ground Cumin</fooditem>
    </ingredient>

    <ingredient>
      <quantity>6</quantity> 
      <unit>packet</unit> 
      <fooditem>Bijol</fooditem>
    </ingredient>

    <ingredient>
      <quantity>6</quantity> 
      <unit>packet</unit> 
      <fooditem>Bijol</fooditem>
    </ingredient>

    <ingredient>
      <quantity>5</quantity> 
      <unit>C.</unit> 
      <fooditem>unbleached wheat blend flour</fooditem>
    </ingredient>

    <ingredient>
      <quantity>5</quantity> 
      <unit>lb.</unit> 
      <fooditem>rice</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <unit>lb.</unit> 
      <fooditem>unrefined sugar</fooditem>
    </ingredient>

    <ingredient>
      <quantity>3</quantity> 
      <unit>qt.</unit> 
      <fooditem>olive oil</fooditem>
    </ingredient>

    <ingredient>
      <quantity>18</quantity> 
      <fooditem>egg</fooditem>
    </ingredient>
  </ingredientlist>

</inventory>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/foofoo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<recipe>
  <title>Foofoo</title>

  <ingredientlist>
    <ingredient>
      <quantity>2</quantity> 
      <fooditem>ripe plantains</fooditem>
    </ingredient>

    <ingredient>
      <fooditem>water</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1/4</quantity> 
      <unit>cup</unit> 
      <fooditem>chicherone</fooditem>
    </ingredient>
  </ingredientlist>

  <preparation>
    <step>
	Slit peel of plantains lengthwise.
    </step>
    <step>
	Cut plantains into 1 inch pieces, peels on.
    </step>
    <step>
	Boil plantain chunks in enough water to cover in a
	<equipment>2 qt. pot</equipment>, uncovered, for 10 minutes.
    </step>
    <step>
	Drain plantains and allow to cool until you can handle them.
    </step>
    <step>
	Remove peels (should be easy) and put peeled plantain chunks back
	into pot.
    </step>
    <step>
	Mash plantains with <equipment>potato masher</equipment>.
    </step>
    <step>
	Add chicherone or bacon if desired, stir in.
    </step>
  </preparation>

</recipe>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/arroz_con_pollo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<recipe>
  <title>Arroz con Pollo</title>

  <ingredientlist>
    <ingredient>
      <quantity>2</quantity> 
      <unit>lbs</unit> 
      <fooditem>chicken</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>cup</unit> 
      <fooditem>mojo griollo</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <fooditem>green pepper</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <fooditem>onion</fooditem>
    </ingredient>

    <ingredient>
      <quantity>12</quantity> 
      <unit>cloves</unit> 
      <fooditem>garlic</fooditem>
    </ingredient>

    <ingredient>
      <quantity>10</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>olive oil</fooditem>
    </ingredient>

    <ingredient>
      <quantity>6</quantity> 
      <fooditem>bay leaf</fooditem>
    </ingredient>

    <ingredient>
      <fooditem>salt</fooditem>
    </ingredient>

    <ingredient>
      <quantity>5</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>Saison completa</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1/2</quantity> 
      <unit>tsp</unit> 
      <fooditem>bijol</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>ground cumin</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>cup</unit> 
      <fooditem>manzanilla olives</fooditem>
    </ingredient>

    <ingredient>
      <quantity>3</quantity> 
      <unit>cups</unit> 
      <fooditem>rice</fooditem>
    </ingredient>

    <ingredient>
      <quantity>5</quantity> 
      <unit>cups</unit> 
      <fooditem>water</fooditem>
    </ingredient>
  </ingredientlist>

  <preparation>
    <step>
	Cut up chicken and sprinkle lightly with salt and half of saison 
	completa. Place in bowl or sealable plastic bag and marinate in 
	mojo griollo for at least 1 hour.
    </step>
    <step>
	Peel and chop onion, garlic.
    </step>
    <step>
	Saute onion and garlic in 6 Tbsp. olive oil over medium heat in 
	<equipment>large frying pan</equipment>.
    </step>
    <step>
	Wash, de-seed, and chop green pepper. Add to saute mix to make sofrito.
    </step>
    <step>
	Cook sofrito about 5 minutes, stirring on and off until onions are 
	clear and garlic starts to turn golden. Do not overcook garlic. 
	Set aside (can be made ahead of time).
    </step>
    <step>
	In <equipment>large covered pot</equipment> brown chicken over medium
	heat in batches - reserve marinade.
    </step>
    <step>
	When all chicken has been browned, add sofrito, reserved marinade, and
	all other ingredients (including rest of saison completa and salt to 
	taste), stir, and bring to boil.
    </step>
    <step>
	Reduce heat to simmer, cover, and cook 45 min., stirring occaissionally 
	to prevent bottom from scorching. 
    </step>
  </preparation>

</recipe>
