=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/recipebook.dtd
<!--

RecipeXML - An XML recipe markup language.

Copyright (C) 2005 David Horton
This work is licensed under the Creative Commons Attribution Share-Alike
license.  See http://creativecommons.org/licenses/by/2.0/ for details.

Modified 2014 Richard Newman

-->


<!-- === REQUIRED Hyperlinks for URL references === -->

<!ELEMENT hyperlink (#PCDATA)>
<!ATTLIST hyperlink url CDATA #REQUIRED>


<!-- === OPTIONAL  Information about a recipe === -->

<!ELEMENT author (#PCDATA)>
<!ELEMENT blurb (#PCDATA)>
<!ELEMENT effort (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT preptime (#PCDATA)>
<!ELEMENT source (#PCDATA|hyperlink)*>
<!ELEMENT yield (#PCDATA)>


<!-- === REQUIRED Lists of ingredients === -->

<!ELEMENT fooditem (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!-- FIXME? The mixed-content definition below does not enforce one and
     only one instance of the tags quantity, unit and fooditem. -->
<!ELEMENT ingredient (#PCDATA | quantity | unit | fooditem)*>


<!-- === REQUIRED Elements of preparation === -->

<!ELEMENT equipment (#PCDATA | hyperlink)*>
<!ELEMENT step (#PCDATA | equipment | hyperlink)*>

<!-- === OPTIONAL Elements of preparation === -->
<!-- === MODIFIED Elements of preparation === -->

<!ELEMENT equipmentinv (#PCDATA?, quantity?, equipment)>
<!ELEMENT timeamt (#PCDATA)>
<!ELEMENT timeunit (#PCDATA)>
<!ELEMENT timetype (#PCDATA)>
<!ELEMENT steptime (#PCDATA?, (timeamt, timeunit, timetype?)+)>
<!ELEMENT timedstep (#PCDATA?, step, steptime?)>


<!-- === REQUIRED The main elements of a recipe === -->
<!-- === REQUIRED title, ingredientlist, and preparation  === -->
<!-- === OPTIONAL recipeinfo, serving, notes  === -->

<!ELEMENT title (#PCDATA)>
<!ELEMENT recipeinfo (author | blurb | effort | genre | preptime | source | yield)*>
<!ELEMENT ingredientlist (ingredient)*>
<!ELEMENT preparation (#PCDATA | equipment | step | timedstep | hyperlink)*>
<!ELEMENT serving (#PCDATA | hyperlink)*>
<!ELEMENT notes (#PCDATA | hyperlink)*>


<!-- === REQUIRED And finally, the recipe itself === -->
<!-- === OPTIONAL all items noted with "?" are optional === -->

<!ELEMENT recipe (title, recipeinfo?, ingredientlist, preparation, serving?, notes?)>


<!-- === The following elements provide logical groupings of recipes === -->


<!-- ===  OPTIONAL A section provides logical divisions of a cookbook === -->

<!ELEMENT section (title, recipe+)>


<!-- ===  REQUIRED A cookbook consists of one or more recipes or sections === -->
<!-- ===  MODIFIED so that title is optional  === -->
<!ELEMENT cookbook (title?, (section | recipe)+)>

<!-- ===  REQUIRED inventory === -->

<!ELEMENT equipmentlist (equipment)*>

<!ELEMENT inventory (ingredientlist | equipmentlist)+>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/COP3503su14_Proj3_WenlanT/supplies3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventory PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">

<inventory>
  <equipmentlist>
    <equipment>tostonera</equipment>
    <equipment>plancha</equipment>
    <equipment>mixing bowl</equipment>
    <equipment>mixer</equipment>
    <equipment>small frying pan</equipment>
    <equipment>large frying pan</equipment>
    <equipment>12 qt. pot</equipment>
  </equipmentlist>
</inventory>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/COP3503su14_Proj3_WenlanT/supplies1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventory PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">

<inventory>
  <ingredientlist>
    <ingredient>
      <quantity>8</quantity> 
      <unit>C.</unit> 
      <fooditem>unbleached wheat blend flour</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>can</unit> 
      <fooditem>baking powder</fooditem>
    </ingredient>

    <ingredient>
      <quantity>5</quantity> 
      <unit>lb.</unit> 
      <fooditem>unrefined sugar</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>box</unit> 
      <fooditem>coarse kosher salt</fooditem>
    </ingredient>

    <ingredient>
      <quantity>10</quantity> 
      <fooditem>free-range egg</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>gal.</unit>
      <fooditem>hormone-free milk</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>jar</unit>
      <fooditem>natural peanut butter</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>bottle</unit>
      <fooditem>ketchup</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1/2</quantity> 
      <unit>gal.</unit>
      <fooditem>orange juice</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>box</unit>
      <fooditem>cheerios</fooditem>
    </ingredient>

    <ingredient>
      <quantity>24</quantity> 
      <unit>oz.</unit> 
      <fooditem>organic vegetable oil</fooditem>
    </ingredient>
  </ingredientlist>

  <equipmentlist>
    <equipment>mixing bowl</equipment>
    <equipment>mixer</equipment>
    <equipment>blender</equipment>
    <equipment>small frying pan</equipment>
    <equipment>large frying pan</equipment>
    <equipment>griddle</equipment>
    <equipment>2 qt. pot</equipment>
    <equipment>1 qt. pot</equipment>
    <equipment>10 qt. pot</equipment>
    <equipment>rice cooker</equipment>
  </equipmentlist>
</inventory>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/inventory2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<inventory>
	<ingredientlist>

	  <ingredient>
		  <quantity>8</quantity> 
		  <units>oz.</units> 
		  <fooditem>dry blackeyed peas</fooditem>
	  </ingredient>

	  <ingredient>
		  <quantity>1</quantity> <units>tsp.</units> <fooditem>baking
			  powder</fooditem>
	  </ingredient>

	  <ingredient>
		  <quantity>1</quantity> <units>tsp.</units> <fooditem>unrefined
			  sugar</fooditem>
	  </ingredient>

	  <ingredient>
		  <quantity>-2</quantity>
		  <units>ribs</units>
		  <fooditem>celery</fooditem>
		  , chopped
	  </ingredient>


	  <ingredient>
		  <quantity>1</quantity> 
		  <units>large</units>
		  <fooditem>green pepper</fooditem>
		  ,chopped
	  </ingredient>

	<ingredient>
		<quantity>3</quantity> 
		<units>large</units>
	<fooditem>plum (roma) tomatoes</fooditem>
	, chopped
	</ingredient>

	<ingredient>
		<fooditem>eggs</fooditem>
	</ingredient>

	<ingredient>
		<quantity>2</quantity> 
		<units>tsp.</units> 
		<fooditem>garlic</fooditem>
	</ingredient>

</ingredientlist>

<equipmentlist>

	  <equipment>pot</equipment>
	  <equipment>knif</equipment> 
	  <equipment>microwave</equipment>

</equipmentlist>


</inventory>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/blackbeans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<recipe>
  <title>Black Beans</title>

  <ingredientlist>
    <ingredient>
      <quantity>2</quantity> 
      <unit>cans</unit> 
      <fooditem>black beans</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <fooditem>green pepper</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <fooditem>onion</fooditem>
    </ingredient>

    <ingredient>
      <quantity>6</quantity> 
      <unit>cloves</unit> 
      <fooditem>garlic</fooditem>
    </ingredient>

    <ingredient>
      <quantity>4</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>olive oil</fooditem>
    </ingredient>

    <ingredient>
      <quantity>4</quantity> 
      <fooditem>bay leaf</fooditem>
    </ingredient>

    <ingredient>
      <fooditem>salt</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>tomato paste</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>Saison completa</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>tsp</unit> 
      <fooditem>ground cumin</fooditem>
    </ingredient>
  </ingredientlist>

  <preparation>
    <step>
	Peel and chop onion, garlic.
    </step>
    <step>
	Saute onion and garlic in olive oil over medium heat in 
	<equipment>2 qt. pot</equipment>.
    </step>
    <step>
	Wash, de-seed, and chop green pepper. Add to saute mix to make sofrito.
    </step>
    <step>
	Cook sofrito about 5 minutes, stirring on and off until onions are 
	clear and garlic starts to turn golden. Do not overcook garlic.
    </step>
    <step>
	Open cans and add beans to sofrito, along with rest of ingredients.
	Stir well and heat for at least 15 more minutes.
    </step>
  </preparation>

</recipe>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/COP3503su14_Proj3_WenlanT/cookbook3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<cookbook>

<recipe>
  <title>Ropa Vieja</title>

  <ingredientlist>
    <ingredient>
      <quantity>2</quantity> 
      <unit>lbs</unit> 
      <fooditem>London broil</fooditem>
    </ingredient>

    <ingredient>
      <quantity>4</quantity> 
      <unit>cups</unit> 
      <fooditem>water</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <fooditem>green pepper</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <fooditem>onion</fooditem>
    </ingredient>

    <ingredient>
      <quantity>12</quantity> 
      <unit>cloves</unit> 
      <fooditem>garlic</fooditem>
    </ingredient>

    <ingredient>
      <quantity>6</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>olive oil</fooditem>
    </ingredient>

    <ingredient>
      <quantity>4</quantity> 
      <fooditem>bay leaf</fooditem>
    </ingredient>

    <ingredient>
      <fooditem>salt</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>Saison completa</fooditem>
    </ingredient>

    <ingredient>
      <quantity>2</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>tomato paste</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>ground cumin</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1</quantity> 
      <unit>Tbsp</unit> 
      <fooditem>garlic powder</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1/2</quantity> 
      <unit>cup</unit> 
      <fooditem>manzanilla olives</fooditem>
    </ingredient>
  </ingredientlist>

  <preparation>
    <step>
	Peel and halve one onion. Wash, remove stem and seeds from one
	green pepper and halve it.
    </step>
    <step>
	Put onion, pepper, meat, and water in 
	<equipment>pressure cooker</equipment>, seal and cook under
	pressure for 45 minutes.
    </step>
    <step>
	In the meanwhile, peel and chop other onion, garlic.
    </step>
    <step>
	Saute onion and garlic in olive oil over medium heat in 
	<equipment>large frying pan</equipment>.
    </step>
    <step>
	Wash, de-seed, and chop other green pepper. 
	Add to saute mix to make sofrito.
    </step>
    <step>
	Cook sofrito about 5 minutes, stirring on and off until onions are 
	clear and garlic starts to turn golden. Do not overcook garlic. 
	Set aside (can be made ahead of time).
    </step>
    <step>
	When meat has finished cooking, let pressure cooker cool until it
	is safe to open lid. Drain meat reserving broth, and remove onion
	and pepper. 
    </step>
    <step>
	Shred meat into strands using two forks (whence the name, which 
	means "old clothes").
    </step>
    <step>
	Add the sofrito and spices, along with tomato paste and enough of
	the reserved broth to make the mixture moist but not runny.
    </step>
    <step>
	Cook on low for at least 10 minutes, stirring as needed.
    </step>
    <step>
    </step>
  </preparation>

</recipe>

	<recipe>
		<title>Black Beans</title>
		<ingredientlist>
			<ingredient>
				<quantity>2</quantity> 
				<unit>cans</unit> 
				<fooditem>black beans</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<fooditem>green pepper</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<fooditem>onion</fooditem>
			</ingredient>
			<ingredient>
				<quantity>6</quantity> 
				<unit>cloves</unit> 
				<fooditem>garlic</fooditem>
			</ingredient>
			<ingredient>
				<quantity>4</quantity> 
				<unit>Tbsp</unit> 
				<fooditem>olive oil</fooditem>
			</ingredient>
			<ingredient>
				<quantity>4</quantity> 
				<fooditem>bay leaf</fooditem>
			</ingredient>
			<ingredient>
				<fooditem>salt</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<unit>Tbsp</unit> 
				<fooditem>tomato paste</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<unit>Tbsp</unit> 
				<fooditem>Saison completa</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<unit>tsp</unit> 
				<fooditem>ground cumin</fooditem>
			</ingredient>
		</ingredientlist>
		<preparation>
			<step>
			Peel and chop onion, garlic.
			</step>
			<step>
			Saute onion and garlic in olive oil over medium heat in 
			<equipment>2 qt. pot</equipment>.
			</step>
			<step>
			Wash, de-seed, and chop green pepper. Add to saute mix to make sofrito.
			</step>
			<step>
			Cook sofrito about 5 minutes, stirring on and off until onions are 
			clear and garlic starts to turn golden. Do not overcook garlic.
			</step>
			<step>
			Open cans and add beans to sofrito, along with rest of ingredients.
			Stir well and heat for at least 15 more minutes.
			</step>
		</preparation>
	</recipe>

</cookbook>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/COP3503su14_Proj3_WenlanT/cookbook.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<cookbook>
	<title>happy monkey	</title>

	<section>
		<title>lunchmenu</title>

		<recipe>
			<title>Ants on a Stick</title>
			<ingredientlist>
				<ingredient>
					<quantity>6</quantity> 
					<unit>stalks</unit> 
					<fooditem>celery</fooditem>
				</ingredient>
				<ingredient>
					<quantity>6</quantity> 
					<unit>tbsp.</unit> 
					<fooditem>peanut butter</fooditem>
				</ingredient>
				<ingredient>
					<quantity>1/2</quantity> 
					<unit>cup</unit> 
					<fooditem>raisins</fooditem>
				</ingredient>
			</ingredientlist>
			<preparation>
				<step>
					Wash, trim, and dry celery stalks.
				</step>
				<step>
					Fill each celery stalk with peanut butter.
				</step>
				<step>
				Arrange raisins in a line on peanut butter in celery stalks.
				</step>
			</preparation>
		</recipe>
	</section>
	<section>
		<recipe>
			<title>Arroz con Pollo</title>
			<ingredientlist>
				<ingredient>
					<quantity>2</quantity> 
					<unit>lbs</unit> 
					<fooditem>chicken</fooditem>
				</ingredient>
				<ingredient>
					<quantity>1</quantity> 
					<unit>cup</unit> 
					<fooditem>mojo griollo</fooditem>
				</ingredient>
				<ingredient>
					<quantity>2</quantity> 
					<fooditem>green pepper</fooditem>
				</ingredient>
				<ingredient>
					<quantity>2</quantity> 
					<fooditem>onion</fooditem>
				</ingredient>
				<ingredient>
					<quantity>12</quantity> 
					<unit>cloves</unit> 
					<fooditem>garlic</fooditem>
				</ingredient>
				<ingredient>
					<quantity>10</quantity> 
					<unit>Tbsp</unit> 
					<fooditem>olive oil</fooditem>
				</ingredient>
				<ingredient>
					<quantity>6</quantity> 
					<fooditem>bay leaf</fooditem>
				</ingredient>
				<ingredient>
					<fooditem>salt</fooditem>
				</ingredient>
				<ingredient>
					<quantity>5</quantity> 
					<unit>Tbsp</unit> 
					<fooditem>Saison completa</fooditem>
				</ingredient>
				<ingredient>
					<quantity>1/2</quantity> 
					<unit>tsp</unit> 
					<fooditem>bijol</fooditem>
				</ingredient>
				<ingredient>
					<quantity>2</quantity> 
					<unit>Tbsp</unit> 
					<fooditem>ground cumin</fooditem>
				</ingredient>
				<ingredient>
					<quantity>1</quantity> 
					<unit>cup</unit> 
					<fooditem>manzanilla olives</fooditem>
				</ingredient>
				<ingredient>
					<quantity>3</quantity> 
					<unit>cups</unit> 
					<fooditem>rice</fooditem>
				</ingredient>
				<ingredient>
					<quantity>5</quantity> 
					<unit>cups</unit> 
					<fooditem>water</fooditem>
				</ingredient>
			</ingredientlist>
			<preparation>
				<step>
				Cut up chicken and sprinkle lightly with salt and half of saison 
				completa. Place in bowl or sealable plastic bag and marinate in 
				mojo griollo for at least 1 hour.
				</step>
				<step>
				Peel and chop onion, garlic.
				</step>
				<step>
				Saute onion and garlic in 6 Tbsp. olive oil over medium heat in 
				<equipment>large frying pan</equipment>.
				</step>
				<step>
				Wash, de-seed, and chop green pepper. Add to saute mix to make sofrito.
				</step>
				<step>
				Cook sofrito about 5 minutes, stirring on and off until onions are 
				clear and garlic starts to turn golden. Do not overcook garlic. 
				Set aside (can be made ahead of time).
				</step>
				<step>
				In <equipment>large covered pot</equipment> brown chicken over medium
				heat in batches - reserve marinade.
				</step>
				<step>
				When all chicken has been browned, add sofrito, reserved marinade, and
				all other ingredients (including rest of saison completa and salt to 
				taste), stir, and bring to boil.
				</step>
				<step>
				Reduce heat to simmer, cover, and cook 45 min., stirring occaissionally 
				to prevent bottom from scorching. 
				</step>
			</preparation>
		</recipe>

			<recipe>
		<title>Black Beans</title>
		<ingredientlist>
			<ingredient>
				<quantity>2</quantity> 
				<unit>cans</unit> 
				<fooditem>black beans</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<fooditem>green pepper</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<fooditem>onion</fooditem>
			</ingredient>
			<ingredient>
				<quantity>6</quantity> 
				<unit>cloves</unit> 
				<fooditem>garlic</fooditem>
			</ingredient>
			<ingredient>
				<quantity>4</quantity> 
				<unit>Tbsp</unit> 
				<fooditem>olive oil</fooditem>
			</ingredient>
			<ingredient>
				<quantity>4</quantity> 
				<fooditem>bay leaf</fooditem>
			</ingredient>
			<ingredient>
				<fooditem>salt</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<unit>Tbsp</unit> 
				<fooditem>tomato paste</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<unit>Tbsp</unit> 
				<fooditem>Saison completa</fooditem>
			</ingredient>
			<ingredient>
				<quantity>1</quantity> 
				<unit>tsp</unit> 
				<fooditem>ground cumin</fooditem>
			</ingredient>
		</ingredientlist>
		<preparation>
			<step>
			Peel and chop onion, garlic.
			</step>
			<step>
			Saute onion and garlic in olive oil over medium heat in 
			<equipment>2 qt. pot</equipment>.
			</step>
			<step>
			Wash, de-seed, and chop green pepper. Add to saute mix to make sofrito.
			</step>
			<step>
			Cook sofrito about 5 minutes, stirring on and off until onions are 
			clear and garlic starts to turn golden. Do not overcook garlic.
			</step>
			<step>
			Open cans and add beans to sofrito, along with rest of ingredients.
			Stir well and heat for at least 15 more minutes.
			</step>
		</preparation>
	</recipe>

	</section>

			<recipe>
			<title>Foofoo</title>
			<ingredientlist>
				<ingredient>
					<quantity>2</quantity> 
					<fooditem>ripe plantains</fooditem>
				</ingredient>
				<ingredient>
					<fooditem>water</fooditem>
				</ingredient>
				<ingredient>
					<quantity>1/4</quantity> 
					<unit>cup</unit> 
					<fooditem>chicherone</fooditem>
				</ingredient>
			</ingredientlist>
			<preparation>
				<step>
				Slit peel of plantains lengthwise.
				</step>
				<step>
				Cut plantains into 1 inch pieces, peels on.
				</step>
				<step>
				Boil plantain chunks in enough water to cover in a
					<equipment>2 qt. pot</equipment>, uncovered, for 10 minutes.
				</step>
				<step>
				Drain plantains and allow to cool until you can handle them.
				</step>
				<step>
				Remove peels (should be easy) and put peeled plantain chunks back
				into pot.
				</step>
				<step>
				Mash plantains with <equipment>potato masher</equipment>.
				</step>
				<step>
				Add chicherone or bacon if desired, stir in.
				</step>
			</preparation>
		</recipe>



</cookbook>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/antsOnAStick.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<recipe>
  <title>Ants on a Stick</title>

  <ingredientlist>
    <ingredient>
      <quantity>6</quantity> 
      <unit>stalks</unit> 
      <fooditem>celery</fooditem>
    </ingredient>

    <ingredient>
      <quantity>6</quantity> 
      <unit>tbsp.</unit> 
      <fooditem>peanut butter</fooditem>
    </ingredient>

    <ingredient>
      <quantity>1/2</quantity> 
      <unit>cup</unit> 
      <fooditem>raisins</fooditem>
    </ingredient>
  </ingredientlist>

  <preparation>
    <step>
	Wash, trim, and dry celery stalks.
    </step>
    <step>
	Fill each celery stalk with peanut butter.
    </step>
    <step>
	Arrange raisins in a line on peanut butter in celery stalks.
    </step>
  </preparation>

</recipe>

=== tianwenlan/COP3503-Programming-fundamentals-2/Project/Project3/tostones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe PUBLIC "-//Happy-Monkey//DTD RecipeBook//EN"
"http://www.happy-monkey.net/recipebook/recipebook.dtd">
<recipe>
  <title>Tostones</title>

  <ingredientlist>
    <ingredient>
      <quantity>2</quantity> 
      <fooditem>green plantains</fooditem>
    </ingredient>

    <ingredient>
      <fooditem>oil for frying</fooditem>
    </ingredient>

    <ingredient>
      <fooditem>salt</fooditem>
    </ingredient>
  </ingredientlist>

  <preparation>
	  <equipment>lsdf</equipment>
    <step>
	Cut peel off plantains and cut into 1/2 to 1 inch chunks.
    </step>
    <step>
        Bring oil (at least 2 inches deep) to 280-300 degrees F.
    </step>
    <step>
	Fry plantain chunks for about 2 minutes in batches of 6-7.
    </step>
    <step>
	Drain fried plantain chunks and smash with 
	<equipment>tostonera</equipment> to 1/4 inch thickness
    </step>
    <step>
	Fry flattened plantain chunks for about 2 more minutes in batches of 3-4.
    </step>
    <step>
	Drain and place tostones on paper towels.
    </step>
    <step>
	Lightly salt tostones to taste.
    </step>
  </preparation>

</recipe>
